---
# tasks file for nginx
- name: Create Mandatory resources for NGINX Ingress
  command: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-0.32.0/deploy/static/provider/aws/deploy.yaml

- name: Deploy Nginx Demo App
  command: kubectl apply -f https://raw.githubusercontent.com/jhawthor/aws_kubernetes/master/scripts/nginx_scale_demo.yml

- name: Deploy Horizontal Pod Autoscaler
  command: kubectl apply -f https://raw.githubusercontent.com/jhawthor/aws_kubernetes/master/scripts/hpa.yml