---
# tasks file for app

- name: Deploy Nginx Demo App
  command: kubectl apply -f https://raw.githubusercontent.com/jhawthor/aws_kubernetes/master/scripts/nginx_scale_demo.yml

- name: Deploy Horizontal Pod Autoscaler
  command: kubectl apply -f https://raw.githubusercontent.com/jhawthor/aws_kubernetes/master/scripts/hpa.yml