---
# tasks file for k8_master
- name: Adding kubeadm repositories on the Master Node
  yum_repository:
    name: kube
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Installing Docker & kubeadm on the Master Node
  package:
    name:
      - docker
      - kubeadm
      - iproute-tc
    state: present

- name: Updating IP tables on the Master
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Staring Docker & kubelet on the Master Node
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ service_names }}"

- name: Pulling the images of k8s master
  command: kubeadm config images pull

- name: Updating Docker cgroup on the Master Node
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
      "exec-opts": ["native.cgroupdriver=systemd"]
      }

- name: Restarting Docker on the Master Node
  service:
    name: docker
    state: restarted

- name: Initializing k8s cluster
  # command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem
  command: kubeadm init --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem

- name: Setting up kubectl on the Master Node
  shell:
    cmd: |
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Deploying CNI Deploy a CNI (Weave) on the Master Only
  #command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  command: kubectl apply -f https://cloud.weave.works/k8s/net

- name: Install Metrics Server for HPA
  command: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/download/v0.3.6/components.yaml

- name: Creating token for Slave nodes
  command: kubeadm token create  --print-join-command
  register: token
