kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginxscaledemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: cont1
          image: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 10m
---
kind: Service
apiVersion: v1
metadata:
  name: nginxscaledemo-svc
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
