---
# tasks file for etcdctl
- name: Copy ETCDCTL script
  copy:
    src: https://raw.githubusercontent.com/jhawthor/aws_kubernetes/master/scripts/install-etcdctl.sh
    dest: install-etcdctl.sh
 
- name: Install ETCDCTL
  shell:
    cmd:
      sudo chmod u+x hello_script.sh
      sudo install-etcdctl.sh
