---
# tasks file for etcdctl
 - name: Install ETCDCTL
   shell:
     cmd: |
       export RELEASE="3.3.13"
       wget https://github.com/etcd-io/etcd/releases/download/v${RELEASE}/etcd-v${RELEASE}-linux-amd64.tar.gz
       tar xvf etcd-v${RELEASE}-linux-amd64.tar.gz
       rm -f etcd-v${RELEASE}-linux-amd64.tar.gz
       cd etcd-v${RELEASE}-linux-amd64
       sudo mv etcdctl /usr/local/bin  
    
